# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#  For correction purpose.
Ensure you always create new cell for your code, so that your answer won't override mine.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
zeros= np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
ones= np.ones(10)

#### Create an array of 10 fives

In [7]:
fives=[5,5,5,5,5,5,5,5,5,5]

fives=np.array(fives)
fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [10]:
c=np.arange(10,51)
c


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
mat_3= np.array([[0,1,2],[3,4,5],[6,7,8]])
mat_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [19]:
Ident_3=np.eye(3)
Ident_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create the following matrix:

In [20]:
np.linspace(0,1,50)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [23]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

mat= np.array([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[1,3]

20

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:,0]

array([12, 17, 22])

array([[ 2],
       [ 7],
       [12]])

In [33]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
aa= np.array(np.arange(1,26)).reshape(5,5)
aa.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [34]:
aa[4,1::]

array([22, 23, 24, 25])

### Now do the following

In [63]:
arr = np.random.randint(1,100,100)
arr

array([58, 21, 25, 48, 24, 23, 47, 63, 85, 29, 81, 59, 94, 39, 22, 27, 53,
        7, 14, 30, 81, 11, 39, 25, 42, 39, 34, 89, 31, 57, 84, 78, 66, 58,
       88, 39, 55, 32,  4, 24, 75, 65, 30, 96, 93, 13, 14, 58, 82, 90,  7,
       97,  7, 89,  7, 54, 33, 88, 12, 31, 63, 34, 71, 95, 85, 88,  3, 58,
       60, 79, 43, 86, 90, 72,  8, 59,  8,  7,  9, 19,  8, 36, 24, 97, 33,
       14,  1, 75, 66, 56, 13, 79, 63,  2, 36, 84, 43, 35,  1,  7])

#### Get all the element greater than 80 in the array (arr) above

In [64]:
new= arr[arr>=80]
new

array([85, 81, 94, 81, 89, 84, 88, 96, 93, 82, 90, 97, 89, 88, 95, 85, 88,
       86, 90, 97, 84])

#### return all values that are even number and greater than 50

In [71]:
even=arr[arr>=50]
even_1=[]
for i in even:
    if i%2==0:
        even_1.append(i)
even_1= np.array(even_1)
even_1

array([58, 94, 84, 78, 66, 58, 88, 96, 58, 82, 90, 54, 88, 88, 58, 60, 86,
       90, 72, 66, 56, 84])

####  change the shape of the array to 10x10 matrix

In [46]:
arr= np.random.randint(1,100,100)
arr.reshape(10,10)

array([[77, 38, 96, 55, 92,  4, 54, 75, 26, 25],
       [69, 44, 35, 23, 53,  1, 96, 58, 39, 90],
       [93, 33,  8, 50, 19, 28, 83, 14, 44, 25],
       [59, 40, 51, 45, 66, 81, 39, 40, 99,  3],
       [ 5, 82, 40, 72, 94, 73, 80, 41, 38, 29],
       [90,  6, 18, 74, 30, 49, 87, 51, 62, 13],
       [ 4, 13, 20, 54, 94,  3, 72, 43, 89, 46],
       [34, 71, 86, 40,  6, 63, 87, 20, 23, 43],
       [10, 21, 79,  1, 13, 66, 18, 13, 27, 75],
       [72,  7, 17, 29, 38, 28, 50, 50, 91, 74]])

#### what is the minimum value of the array arr?

In [47]:
arr.min()

1

#### what is the index of te minimum value of the array arr?

In [48]:
arr.argmin()

15

#### what is the maximum value of the array arr?

In [49]:
arr.max()

99

#### what is the index of te minimum value of the array arr?

In [51]:
arr.argmax()

38

# Great Job!